// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/device-types": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deviceType"
                ],
                "summary": "Lists all device types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.DeviceType"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deviceType"
                ],
                "summary": "Add device type",
                "parameters": [
                    {
                        "description": "Device type payload",
                        "name": "deviceType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.DeviceTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.DeviceType"
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/domain.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/device-types/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deviceType"
                ],
                "summary": "Returns the device type based on the id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device type id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.DeviceType"
                        }
                    },
                    "404": {
                        "description": "device_type not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deviceType"
                ],
                "summary": "Update device type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device type id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Device type payload",
                        "name": "deviceType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.DeviceTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.DeviceType"
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/domain.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "device_type not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "deviceType"
                ],
                "summary": "Delete device type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device type id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "404": {
                        "description": "device_type not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/devices": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Lists all devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Device"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Add a device",
                "parameters": [
                    {
                        "description": "device payload",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.DeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Device"
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/domain.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/devices/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Returns the device with specified id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Device"
                        }
                    },
                    "404": {
                        "description": "device not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "devices"
                ],
                "summary": "Update device based on id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "device id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "device payload",
                        "name": "device",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.DeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Device"
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/domain.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "device not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "devices"
                ],
                "summary": "Delete device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "device id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "404": {
                        "description": "device not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/devices/{id}/sensors": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deviceSensors"
                ],
                "summary": "Lists all sensors of selected device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "device id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.SensorType"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deviceSensors"
                ],
                "summary": "Add sensor to device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "device id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Associated sensor payload",
                        "name": "sensorId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AssociateSensorRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "status no content"
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/domain.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/devices/{id}/sensors/{sensorId}": {
            "delete": {
                "tags": [
                    "deviceSensors"
                ],
                "summary": "Delete sensor from device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "device id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "sensor id",
                        "name": "sensorId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "status no content"
                    },
                    "404": {
                        "description": "sensors_devices not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Check connection with db",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Db offline",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/readings/dht/{deviceId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "readings"
                ],
                "summary": "Lists all dht readings of deiveceId in range from - to and limit number of lines",
                "parameters": [
                    {
                        "type": "string",
                        "description": "device id",
                        "name": "deviceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "time stamp start query (default 24h ago)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "time stamp stop query (default now)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max number of lines (default 500)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.DhtReadings"
                            }
                        }
                    },
                    "400": {
                        "description": "input parameters not valid",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readings/dht/{deviceId}/latest": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "readings"
                ],
                "summary": "Returns latest dht reading",
                "parameters": [
                    {
                        "type": "string",
                        "description": "device id",
                        "name": "deviceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.DhtReadings"
                        }
                    },
                    "404": {
                        "description": "latest dht reading not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readings/status/{deviceId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "readings"
                ],
                "summary": "Lists all status readings of deiveceId in range from - to and limit number of lines",
                "parameters": [
                    {
                        "type": "string",
                        "description": "device id",
                        "name": "deviceId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "time stamp start query (default 24h ago)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "time stamp stop query (default now)",
                        "name": "to",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max number of lines (default 500)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.StatusReadings"
                            }
                        }
                    },
                    "400": {
                        "description": "input parameters not valid",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/readings/status/{deviceId}/latest": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "readings"
                ],
                "summary": "Returns latest status reading",
                "parameters": [
                    {
                        "type": "string",
                        "description": "device id",
                        "name": "deviceId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.StatusReadings"
                        }
                    },
                    "404": {
                        "description": "latest status reading not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/rooms": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "lists all rooms",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Room"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Create a new room",
                "parameters": [
                    {
                        "description": "Room payload",
                        "name": "room",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RoomRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Room"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/rooms/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "returns the rooms with the specified id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Room"
                        }
                    },
                    "404": {
                        "description": "room not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rooms"
                ],
                "summary": "Update room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RoomId",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Room payload",
                        "name": "room",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.RoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Room"
                        }
                    },
                    "400": {
                        "description": "invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "room not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "rooms"
                ],
                "summary": "Delete the room",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "404": {
                        "description": "room not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sensor-types": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensorTypes"
                ],
                "summary": "Lists all sensor types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.SensorType"
                            }
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensorTypes"
                ],
                "summary": "Add new sensor type",
                "parameters": [
                    {
                        "description": "Sensor type payload",
                        "name": "sensorType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SensorTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.SensorType"
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/domain.ValidationErrorResponse"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/sensor-types/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensorTypes"
                ],
                "summary": "Returns sensor type with specified id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SensorType ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.SensorType"
                        }
                    },
                    "404": {
                        "description": "sensor_type not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sensorTypes"
                ],
                "summary": "Update sensor type based on id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sensor type id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "sensor type payload",
                        "name": "sensorType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.SensorTypeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.SensorType"
                        }
                    },
                    "400": {
                        "description": "validation error",
                        "schema": {
                            "$ref": "#/definitions/domain.ValidationErrorResponse"
                        }
                    },
                    "404": {
                        "description": "sensor_type not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "sensorTypes"
                ],
                "summary": "Delete sensor type based on id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sensor type id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "no content"
                    },
                    "404": {
                        "description": "Sensor type not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.AssociateSensorRequest": {
            "type": "object",
            "required": [
                "sensor_id"
            ],
            "properties": {
                "sensor_id": {
                    "type": "string"
                }
            }
        },
        "domain.ColumnSchemaType": {
            "type": "object",
            "required": [
                "column",
                "type"
            ],
            "properties": {
                "column": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "float",
                        "int",
                        "bool",
                        "string"
                    ]
                }
            }
        },
        "domain.Device": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "device_type": {
                    "$ref": "#/definitions/domain.DeviceType"
                },
                "id": {
                    "type": "string"
                },
                "room": {
                    "$ref": "#/definitions/domain.Room"
                }
            }
        },
        "domain.DeviceRequest": {
            "type": "object",
            "required": [
                "code",
                "device_type_id"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "maxLength": 50
                },
                "device_type_id": {
                    "type": "string"
                },
                "room_id": {
                    "type": "string"
                }
            }
        },
        "domain.DeviceType": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "domain.DeviceTypeRequest": {
            "type": "object",
            "required": [
                "code",
                "topic"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "topic": {
                    "type": "string",
                    "maxLength": 50
                }
            }
        },
        "domain.DhtReadings": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string"
                },
                "humidity": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "sensor_id": {
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "domain.Room": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.RoomRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.SensorType": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "column_schema": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/domain.ColumnSchemaType"
                    }
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "payload_format": {
                    "type": "string"
                },
                "qos_mqtt": {
                    "type": "integer"
                },
                "readings_table_name": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                },
                "value_mapping": {
                    "type": "object"
                }
            }
        },
        "domain.SensorTypeRequest": {
            "type": "object",
            "required": [
                "code",
                "column_schema",
                "payload_format",
                "readings_table_name",
                "topic"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "column_schema": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/domain.ColumnSchemaType"
                    }
                },
                "description": {
                    "type": "string"
                },
                "payload_format": {
                    "type": "string",
                    "enum": [
                        "json",
                        "raw"
                    ]
                },
                "qos_mqtt": {
                    "type": "integer",
                    "maximum": 2,
                    "minimum": 0
                },
                "readings_table_name": {
                    "type": "string"
                },
                "topic": {
                    "type": "string",
                    "maxLength": 50
                },
                "value_mapping": {
                    "type": "object"
                }
            }
        },
        "domain.StatusReadings": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "sensor_id": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "domain.ValidationErrorResponse": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3030",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "IOT nonna core API",
	Description:      "API for management of IoT system database",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
